services:
  sift:
    build: .
    image: sift-workstation:latest
    container_name: sift-workstation
    hostname: sift-workstation

    privileged: true
    cap_add:
      - SYS_ADMIN
      - MKNOD
    devices:
      - /dev/fuse

    ports:
      - "5901:5901"
      - "6901:6901"
      - "2222:22"
      - "3113:3113"

    env_file:
      - ../../.env

    environment:
      - VNC_RESOLUTION=1280x800
      - VNC_COL_DEPTH=24

    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ../evidence:/home/sift/evidence
      - ../workflows:/home/sift/workflows
      - ../playbooks:/home/sift/playbooks

    restart: unless-stopped
